[tool.poetry]
name = "langchain"
version = "0.1.0"
description = "Experiments with langchain"
authors = ["Anmol Gupta <agupta@cs.iitr.ac.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
